version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "telemetry"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ab00oe6jdqsp"
s3_prefix = "telemetry"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
